### ISSUE TITLE
Reorganizacja repozytorium symfony-docs-pl

### ISSUE THREAD

**Issue by abutronik** [symfony-docs-pl/symfony-docs-pl#3]
@chrisbujok, @sinevar , @SongoQ , @whisller 

Panowie, nasze repo przestało być konserwowane przez @SongoQ co najmniej od początku tego roku. Doprowadziło to do rozjechania się gałęzi master i 2.3. PR z moimi uzupełnieniami i poprawkami tkwił nie ruszony od lutego b.r. i już teraz nie dał się scalić, bo powstały konflikty z drobnymi patchami naniesionymi w międzyczasie a nowych tłumaczeń miałem bardzo dużo. Chciałem, to jakoś naprawić i przez omyłkę skasowałem nasze repo zamiast swojego (okazuje się. że o taką pomyłkę jest bardzo łatwo). Ale nie ma złego, co na dobre nie wychodzi. Odtworzyłem repo symfony-docs-pl/symfony-docs-pl ze swojej lokalnej kopii i przypuszczalnie żadne istotne zatwierdzenia nie ucierpiały. Z tym, że zrezygnowałem z  gałęzi 2.3, bo w naszym przypadku prowadziło to do błędów (aktualizowana była master a 2.3 nie). Oryginalna dokumentacja jest cały czas aktualizowana i jest już dokumentowana gałąź 2.5. Nasza dokumentacja wymaga uzupełnień i poprawek. Podtrzymuje swoją opinię, że prowadzenie gałęzi dla poszczególnych wersji nie ma sensu w naszym przypadku. Od lutego przetłumaczyłem dość znaczny materiał i już go scaliłem w gałęzi master nowego repo. Niestety szlag  trafił istniejący klucz i haki (jeśli byly) i automatyczna aktualizacja w domenie symfony-docs.pl przestała działać. Niestety @SongoQ nie opisał tej kwestii i nie mogłem tego sam naprawić. Połączyłem więc nasze repo z serwisem ReadTheDocs i aktualna dokumentacja jest prezentowana pod adresem http://symfony2-docs-pl.readthedocs.org. Nic nie stoi na przeszkodzie, aby naprawić połączenie z http://symfony-docs.pl, ale to praca dla @SongoQ (jeśli chce się jeszcze z nami bawić).

Co do publikowania na serwisie ReadTheDocs, to sprawa jest banalna. Na razie ja zarządzam ta publikacją, ale możemy uzgodnić co innego.

No cóż, przykro mi, że będziecie musieli jeszcze raz wykonać fork ze wzorcowego repo, ale może się okazać, że to była ozdrowieńcza pomyłka.

Pozdrawiam @abutronik.

**Comment by sinevar** [comment]
@abutronik Dzięki za włożoną pracę i bycie jednym z najaktywniejszych osób w tej grupie. Czyli jeśli dobrze Cię zrozumiałem, to główna strona http://symfony-docs.pl nie posiada najaktualniejszej wersji tak? I od teraz wszystko jest generowane http://symfony2-docs-pl.readthedocs.org ?

Jeśli chodzi o tłumaczenie gałęzi - w zupełności się z Tobą zgadzam.

**Comment by abutronik** [comment]
Witaj,
fajnie że się ktoś wreszcie odezwał.

Tak jest. Strona http://symfony-docs.pl nie jest obsługwana przez 
@SongoQ już prawie od półtora roku i jest mocno nieaktualna. Aktualna 
natomiast jest dokumentacja na readthedocs.org - jest ona generowana 
automatycznie w kilku wersjach HTML i PDF. Problem jednak jest. Symfony 
sie bardzo szybko rozwija i dokumentacja też się zmienia. W wersji 2.7 
jest to praktycznie całkiem nowa rzecz (w zakresie podręcznika, 
krótkiego kursu i nowych części) i już są uzupełnienia dla wersji 3.0, 
która nadchodzi wielkimi krokami. Pojęcie "Dokumentacja Syfony 2" jest 
już archaizmem. Musimy mówić o "Dokumentacji Symfony".
Priorytetem musi być tłumaczenie wersji 2.7, która jest najnowszą wersją 
LTE. W naszym projekcie gałąź  master 2.7 jest taka sama jak (na razie).

  Zaktualizowałem do wersji 2.7 kilka rozdziałów ale jest to "kropla w 
morzu potrzeb". Jeśli chcemy kontynuować ten projekt, to trzeba się 
zastanowić nad nową organizacją pracy. Na tapecie mam tłumaczenie 
quick-tour/big_picture i dokończę pozostałe rozdziały quick-tour + kilka 
innych poprawek (do końca miesiąca).

Pozdrawiam :-)

W dniu 23.08.2015 o 15:03, Adam Gegotek pisze:
