### ISSUE TITLE
[WIP] Przetłumaczenie /best_practices/*  w. 2.7

### ISSUE THREAD

**Issue by abutronik** [symfony-docs-pl/symfony-docs-pl#50]
Postaram się przetłumaczyć tu wszystko.
Termin: koniec sierpnia 2015

**Comment by CzarCzeslaw** [comment]
Czesc,
Jak idzie tłumaczenie ?
Szczegolnie zainteresowany jestem częścią /cookbook/forms
Czy mozna wam jakoś pomóc ?

**Comment by abutronik** [comment]
Witaj!

Dzięki za ofertę współpracy. Twoja pomoc jest mile widziana. Postępuj 
zgodnie z instrukcją opisaną w https://github.com/symfony-docs-pl/ideas. 
W razie niejaśności, służę pomocą.

Pozdrawiam.

W dniu 05.01.2016 o 13:40, CzarCzeslaw pisze:
